export const GET_USERS = "GET_USERS";
export const GET_BOOKS = "GET_BOOKS";
export const TOGGLE_IS_LOADING_BOOK = "TOGGLE_IS_LOADING_BOOK";
export const SET_BOOK_AUTOLOAD = "SET_BOOK_AUTOLOAD";
export const SET_USERS_AUTOLOAD = "SET_USERS_AUTOLOAD";
export const INCREMENT_CURRENT_BOOK_ID = "INCREMENT_CURRENT_BOOK_ID";
